apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: aroti
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres123"
  DATABASE_URL: "postgresql://postgres:postgres123@postgres:5432/aroti"
